In [1]:
import torch

# 2.3.1. Scalars

In [3]:
x = torch.tensor(3.0)
x

tensor(3.)

In [7]:
y = torch.tensor(2.0)
y

tensor(2.)

In [8]:
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# 2.3.2. Vectors

In [9]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [10]:
x[2]

tensor(2)

In [11]:
len(x)

3

In [12]:
x.shape

torch.Size([3])

# 2.3.3. Matrices

In [13]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [14]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [15]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [16]:
A.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [17]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# 2.3.4. Tensors

In [18]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# 2.3.5. Basic Properties of Tensor Arithmetic

In [19]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [20]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [21]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

# 2.3.6. Reduction

In [22]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [23]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [24]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [28]:
A.shape, A.sum(axis=0)

(torch.Size([2, 3]), tensor([3., 5., 7.]))

In [29]:
A.shape, A.sum(axis=1)

(torch.Size([2, 3]), tensor([ 3., 12.]))

In [30]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [31]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [32]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))